apiVersion: v1
kind: Service
metadata:
  name: frontend-service-2022bcd0025
spec:
  selector:
    app: book-review-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # You can access it via http://<minikube-ip>:30007
